name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Trigger on pushes to the 'master' branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 23

    # Install dependencies and build
    - name: Install and build
      run: |
        npm install
        npm run build

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./dist
